# @package dataset
# https://www.kaggle.com/datasets/ipythonx/wikiart-gangogh-creating-art-gan
# tylko folder landscape
name:
  impresionism
load:
  _target_: torchvision.datasets.ImageFolder
  root: ${paths.datasets}/impresionism

transform:
  _target_: torchvision.transforms.Compose
  transforms:
#    - _target_: torchvision.transforms.CenterCrop
#      size:
#        - ${model.input_size}
#        - ${model.input_size}
    - _target_: torchvision.transforms.Resize
      size:
        - ${model.input_size}
        - ${model.input_size}
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [ 0.5, 0.5, 0.5 ]
      std: [ 0.5, 0.5, 0.5 ]
data_loader:
  batch_size: 128
  shuffle: True
