# @package dataset
# https://www.kaggle.com/datasets/arnaud58/landscape-pictures?select=00000000_%285%29.jpg
name:
  landscape
load:
  _target_: torchvision.datasets.ImageFolder
  root: ${paths.datasets}/Landscape

transform:
  _target_: torchvision.transforms.Compose
  transforms:

    - _target_: torchvision.transforms.Resize
      size:
        - ${model.input_size}
        - ${model.input_size}
    - _target_: torchvision.transforms.CenterCrop
      size:
        - ${model.input_size}
        - ${model.input_size}
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: [ 0.5, 0.5, 0.5 ]
      std: [ 0.5, 0.5, 0.5 ]
data_loader:
  batch_size: 32
  shuffle: True
