defaults:
  - dataset: landscape
  - model: dgan128

  - paths
  - hydra/hydra
  - hydra/job_logging
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


hydra:
  mode:
    RUN
  sweeper:
    params:
      dataset: glob(*)
      model: glob(*)

version:
  0.1.0