# @package model

name:
  dgan128
load:
  _target_: src.model_preparation.dgan128.DGAN128


latent_size:
  128
batch_size:
  ${dataset.data_loader.batch_size}
epochs:
  200
lr:
  1e-4

input_size:
  128

compile:
  true